[project]
name = "openai audio translator poc"
version = "0.1.0"
description = "python based poc for openai translator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.65.5",
    "python-dotenv>=1.0.1",
    "pytube>=15.0.0",
    "pytubefix>=8.12.2",
]
